"""
Generate ndispers/_compiled/<ClassName>.py for every medium.

Each module holds the numpy functions that sympy's lambdify would build at
run time for that class - one per (expression, polarization) - plus the LaTeX
of its index formulas, so that evaluating a medium needs neither sympy nor a
code-generation pause on first use.

Run after editing any medium, _baseclass.py or groups/_base.py:

    uv run python tools/compile_media.py

test_regressions.py::test_compiled_modules_are_current fails until you do.
"""
import hashlib
import re
import inspect
import sys
from pathlib import Path

import sympy
from sympy.utilities import lambdify

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import ndispers  # noqa: E402
import ndispers.media.crystals as C  # noqa: E402
import ndispers.media.glasses as G  # noqa: E402
from ndispers._baseclass import Medium  # noqa: E402
from ndispers.groups._base import BiaxialGroup  # noqa: E402

OUT = ROOT / "ndispers" / "_compiled"
EXPRS = ["n", "dn_wl", "d2n_wl", "d3n_wl", "GD", "GV", "ng", "GVD", "TOD",
         "woa_theta", "woa_phi", "dndT", "dndT2"]


def source_hash(cls):
    """Hash of everything the generated code depends on: the medium's own file
    and the source of every *_expr method it inherits (so an edit elsewhere in
    _baseclass.py - a docstring, pmAngles - does not invalidate 60 modules)."""
    h = hashlib.sha256(Path(sys.modules[cls.__module__].__file__).read_bytes())
    for klass in cls.__mro__[1:]:
        for name, obj in sorted(vars(klass).items()):
            if name.endswith("_expr") or name == "_n_axis":
                h.update(inspect.getsource(obj).encode())
    return h.hexdigest()


def media_classes():
    for mod in (C, G):
        for name in sorted(dir(mod)):
            obj = getattr(mod, name)
            if isinstance(obj, type) and issubclass(obj, Medium) and not name.startswith("_"):
                yield obj


def compile_class(cls):
    x = cls()
    symbols = [s._sympy_() for s in x.symbols]
    funcs, latex, srcs = [], {}, []
    pols = list(dict.fromkeys([x._default_pol, "o", "e"]))
    for pol in pols:
        try:
            n_expr = x.n_expr(pol)
        except Exception:
            continue                                  # e.g. SLN has no o-ray
        latex[pol] = sympy.latex(n_expr)
        for name in EXPRS:
            expr = getattr(x, f"{name}_expr")(pol)
            f = lambdify(symbols, expr, "numpy", cse=True)
            funcs.append(((f"{name}_expr", pol), f))
    if isinstance(x, BiaxialGroup):
        for axis in "xyz":
            expr = getattr(x, f"n_{axis}_expr")()
            f = lambdify(symbols, expr, "numpy", cse=True)
            funcs.append(((f"n_{axis}", x._default_pol), f))

    lines = [
        '"""Generated by tools/compile_media.py - do not edit."""',
        "from numpy import *  # noqa: F401,F403  (the namespace lambdify evaluates in)",
        "",
        f"CLASS = {cls.__module__ + '.' + cls.__qualname__!r}",
        f"SOURCE_HASH = {source_hash(cls)!r}",
        f"LATEX = {latex!r}",
        "",
    ]
    names = []
    for i, (key, f) in enumerate(funcs):
        src = inspect.getsource(f).replace("def _lambdifygenerated(", f"def _f{i}(", 1)
        # lambdify renames the symbol 'lambda' (a keyword) to a fresh dummy
        # each run; call it wl so the output is reproducible
        dummy = re.match(r"def _f\d+\((\w+)", src).group(1)
        src = re.sub(rf"\b{dummy}\b", "wl", src)
        lines.append(src.rstrip())
        lines.append("")
        names.append(f"    {key!r}: _f{i},")
    lines += ["FUNCS = {", *names, "}", ""]
    (OUT / f"{cls.__name__}.py").write_text("\n".join(lines))
    return len(funcs)


def main():
    OUT.mkdir(exist_ok=True)
    (OUT / "__init__.py").write_text(
        '"""Pre-generated numpy functions for every medium; see tools/compile_media.py."""\n')
    classes = list(media_classes())
    stale = {p.stem for p in OUT.glob("*.py") if p.stem != "__init__"} - {c.__name__ for c in classes}
    for name in stale:
        (OUT / f"{name}.py").unlink()
    total = 0
    for cls in classes:
        n = compile_class(cls)
        total += n
        print(f"{cls.__name__:32s} {n:4d} functions")
    print(f"{len(classes)} media, {total} functions"
          + (f", removed {sorted(stale)}" if stale else ""))


if __name__ == "__main__":
    main()
